/**
 * This file is part of WebP2P.
 *
 * WebP2P is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * WebP2P is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with WebP2P.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Filename:    WebP2PAPI.hpp
 * Author(s):   Dries Staelens (partly auto-generated by Firebreath)
 * Copyright:   Copyright (c) 2010 Dries Staelens
 * Description: Definition of the browser plug-in javascript API.
**/

#pragma once

/* STL includes */
#include <string>
#include <sstream>

/* Boost includes */
#include <boost/weak_ptr.hpp>

/* Firebreath includes */
#include "JSAPIAuto.h"
#include "BrowserHost.h"

/* WebP2P includes */
#include "WebP2P.hpp"

class WebP2PAPI : public FB::JSAPIAuto
{
public:
    WebP2PAPI(WebP2PPtr plugin, FB::BrowserHostPtr host);
    virtual ~WebP2PAPI();

    WebP2PPtr getPlugin();

    FB::JSAPIPtr createConnectionPeer(const std::string& serverConfiguration);

private:
    WebP2PWeakPtr m_plugin;
    FB::BrowserHostPtr m_host;
};

